# Installs the build into a temporary DESTDIR and checks the holonight-packaged activation files.
# Usage: cmake -DBUILD_DIR=<dir> -DSTAGE_DIR=<dir> -P check_install.cmake
file(REMOVE_RECURSE "${STAGE_DIR}")
file(MAKE_DIRECTORY "${STAGE_DIR}")
execute_process(
  COMMAND ${CMAKE_COMMAND} -E env "DESTDIR=${STAGE_DIR}" ${CMAKE_COMMAND} --install "${BUILD_DIR}" --prefix /usr
  RESULT_VARIABLE install_result OUTPUT_QUIET ERROR_VARIABLE install_error)
if(NOT install_result EQUAL 0)
  message(FATAL_ERROR "install into DESTDIR failed: ${install_error}")
endif()

set(binary "${STAGE_DIR}/usr/bin/holonight-packaged")
set(dbus_service "${STAGE_DIR}/usr/share/dbus-1/services/org.holonight.Packages1.service")
set(unit "${STAGE_DIR}/usr/lib/systemd/user/holonight-packaged.service")
set(interface_xml "${STAGE_DIR}/usr/share/dbus-1/interfaces/org.holonight.Packages1.Updates.xml")
foreach(path IN ITEMS "${binary}" "${dbus_service}" "${unit}" "${interface_xml}")
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "missing from install stage: ${path}")
  endif()
endforeach()

file(READ "${dbus_service}" dbus_text)
file(READ "${unit}" unit_text)
if(NOT unit_text MATCHES "Type=dbus")
  message(FATAL_ERROR "unit is not Type=dbus")
endif()
if(NOT dbus_text MATCHES "Name=([^\n]+)\n" )
  message(FATAL_ERROR "D-Bus service file has no Name=")
endif()
set(bus_name "${CMAKE_MATCH_1}")
if(NOT unit_text MATCHES "BusName=${bus_name}\n")
  message(FATAL_ERROR "unit BusName does not match D-Bus service Name ${bus_name}")
endif()
if(NOT dbus_text MATCHES "SystemdService=holonight-packaged.service")
  message(FATAL_ERROR "D-Bus service does not point at the systemd unit")
endif()
foreach(text IN ITEMS "${dbus_text}" "${unit_text}")
  if(NOT text MATCHES "/usr/bin/holonight-packaged")
    message(FATAL_ERROR "activation file does not execute the installed binary under the prefix")
  endif()
  if(text MATCHES "${STAGE_DIR}")
    message(FATAL_ERROR "activation file leaks the staging directory")
  endif()
endforeach()
